name = "odcf-hdxpub"
type = "webpack"
workers_dev = true
account_id = "aa60a83e6cccb64d75548d5c63ef80a7"
zone_id = "5ed2ed443005e6dcca19d2079716799a"
kv_namespaces = [
    { binding = "BUCKET", id = "4b5ac5905b234effb9ac84f592f4e11b" }
]

[env.staging]
name = "drive-staging"
